Create js.dockerfile
getgauge-contrib/gauge-docker pull request #2
Opened 2018-09-20 04:02 UTC by kriju

Running dockerized "npm tests" using gauge+taiko. Comments inside the file give details of the need of each step.

2018-09-24 06:13 UTC, sriv requested changes

2018-09-24 06:13 UTC, sriv commented on js.dockerfile
> +RUN apt-key adv --keyserver hkp://pool.sks-keyservers.net --recv-keys 023EDB0B
it is recommended to combine multiple `RUN` to reduce the intermediate layers, and thus reducing the image size.

2018-09-24 06:13 UTC, sriv commented on js.dockerfile
> +COPY taiko.js /app/node_modules/taiko/lib/taiko.js
see https://github.com/getgauge/taiko/issues/164. I think this is better fixed upstream. Feel free to send a PR against it :)

2018-09-24 06:13 UTC, sriv commented on js.dockerfile
> +RUN groupadd -r gguser && useradd -r -g gguser -G audio,video gguser \
generally I'd insist on running things as an unprivileged user. But in a container, I've usually seen `root` being used more liberally, particularly if you would like it to server downstream dockerfiles.

However, I speak from experience, not as an authority on Docker. So please educate me if this is a good practice.

2018-09-24 06:13 UTC, sriv commented on js.dockerfile
> +    && apt-get -y install sudo \
If you end up not having to use a different user, then `sudo` becomes redundant. See comment below.

2018-09-24 06:13 UTC, sriv commented on js.dockerfile
> +RUN apt-get install -y gauge git \
You may want to use `git-all` instead of `git`. See https://git-scm.com/book/en/v2/Getting-Started-Installing-Git#_installing_on_linux

2018-09-24 06:13 UTC, sriv commented on js.dockerfile
> +ADD https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64 /usr/local/bin/dumb-init
I don't see an `ENTRYPOINT` corresponding to `dumb-init` - am I missing something? I am referring to [`dumb-init` usage](https://github.com/Yelp/dumb-init/#usage)

2018-09-25 06:42 UTC, kriju commented
I am using the given [Dockerfile](https://github.com/getgauge-contrib/gauge-docker/blob/master/taiko.dockerfile) already. This serves my project needs as well as takes care of the points you have raised. Thanks for taking time to review and respond on this PR.

2018-09-25 06:42 UTC, closed without merging